title: Cage
email: cage@faraday.io
description: > # this means to ignore newlines until "baseurl:"
  Develop and deploy multi-container Docker applications
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cage.faraday.io" # the base hostname & protocol for your site
twitter_username: faradayio
github_username:  faradayio
permalink: /:slug

# Build settings
markdown: kramdown
highlighter: rouge